import type { Locale } from "@/lib/i18n";

const labels = {
  en: {
    busy: "The simulator is in use. Stop the other live view or training job, then retry.",
    expired: "The live session expired. Start a new live view.",
    stopped: "Live view stopped",
    recordedJoints: "Last reported joint state",
    start: "Start live simulation",
    stop: "Stop live view",
    starting: "Starting Isaac Sim…",
    warming:
      "The GPU is preparing the scene. The first frame can take a minute.",
    live: "Live Isaac Sim",
    recorded: "Recorded preview",
    stale: "Feed interrupted · last frame",
    failed: "Live view is unavailable. Retry when the simulator is ready.",
    cameraError: "Camera update failed. Try again.",
    stopError: "Stop was not confirmed. The session will expire automatically.",
    hint: "Drag to orbit · Shift-drag to pan · Scroll to zoom · Click a robot to inspect",
    keys: "Arrow keys orbit; Shift + arrows pan; + and − zoom; R resets the camera.",
    orbitLeft: "Orbit left",
    orbitRight: "Orbit right",
    orbitUp: "Orbit up",
    orbitDown: "Orbit down",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "Reset camera",
    fullscreen: "Full screen",
    exitFullscreen: "Exit full screen",
    inspect: "Inspect robot",
    select: "Select a robot",
    focus: "Focus camera on robot",
    joints: "Live joint state",
    position: "Position",
    velocity: "Velocity",
    joint: "Joint",
    provenance:
      "Simulated diagnostic motion · native rendered frames · no physical robot commands",
    age: "Frame age",
    frame: "Frame",
    fps: "frames/s",
    overview: "Factory overview",
    replay: "Recorded run",
  },
  es: {
    busy: "El simulador está en uso. Detén la otra vista en vivo o el entrenamiento y reintenta.",
    expired: "La sesión en vivo ha caducado. Inicia una nueva vista en vivo.",
    stopped: "Vista en vivo detenida",
    recordedJoints: "Último estado articular recibido",
    start: "Iniciar simulación en vivo",
    stop: "Detener vista en vivo",
    starting: "Iniciando Isaac Sim…",
    warming:
      "La GPU está preparando la escena. El primer fotograma puede tardar un minuto.",
    live: "Isaac Sim en vivo",
    recorded: "Vista previa grabada",
    stale: "Señal interrumpida · último fotograma",
    failed:
      "La vista en vivo no está disponible. Reintenta cuando el simulador esté listo.",
    cameraError: "No se pudo mover la cámara. Reinténtalo.",
    stopError: "No se confirmó la parada. La sesión caducará automáticamente.",
    hint: "Arrastra para orbitar · Mayús y arrastre para desplazar · Rueda para acercar · Clic en un robot para inspeccionar",
    keys: "Las flechas orbitan; Mayús y flechas desplazan; + y − acercan y alejan; R restablece la cámara.",
    orbitLeft: "Orbitar a la izquierda",
    orbitRight: "Orbitar a la derecha",
    orbitUp: "Orbitar hacia arriba",
    orbitDown: "Orbitar hacia abajo",
    zoomIn: "Acercar",
    zoomOut: "Alejar",
    reset: "Restablecer cámara",
    fullscreen: "Pantalla completa",
    exitFullscreen: "Salir de pantalla completa",
    inspect: "Inspeccionar robot",
    select: "Selecciona un robot",
    focus: "Centrar cámara en el robot",
    joints: "Estado articular en vivo",
    position: "Posición",
    velocity: "Velocidad",
    joint: "Articulación",
    provenance:
      "Movimiento diagnóstico simulado · fotogramas nativos · sin órdenes a robots físicos",
    age: "Antigüedad del fotograma",
    frame: "Fotograma",
    fps: "fotogramas/s",
    overview: "Vista general de fábrica",
    replay: "Ejecución grabada",
  },
  de: {
    busy: "Der Simulator wird verwendet. Andere Live-Ansicht oder Training beenden und erneut versuchen.",
    expired: "Die Live-Sitzung ist abgelaufen. Eine neue Live-Ansicht starten.",
    stopped: "Live-Ansicht beendet",
    recordedJoints: "Zuletzt gemeldeter Gelenkzustand",
    start: "Live-Simulation starten",
    stop: "Live-Ansicht beenden",
    starting: "Isaac Sim startet…",
    warming:
      "Die GPU bereitet die Szene vor. Das erste Bild kann eine Minute dauern.",
    live: "Isaac Sim live",
    recorded: "Aufgezeichnete Vorschau",
    stale: "Übertragung unterbrochen · letztes Bild",
    failed:
      "Live-Ansicht nicht verfügbar. Erneut versuchen, sobald der Simulator bereit ist.",
    cameraError: "Kamera konnte nicht bewegt werden. Erneut versuchen.",
    stopError:
      "Beenden wurde nicht bestätigt. Die Sitzung läuft automatisch ab.",
    hint: "Ziehen zum Drehen · Umschalt und Ziehen zum Verschieben · Scrollen zum Zoomen · Roboter zum Prüfen anklicken",
    keys: "Pfeiltasten drehen; Umschalt und Pfeile verschieben; + und − zoomen; R setzt die Kamera zurück.",
    orbitLeft: "Nach links drehen",
    orbitRight: "Nach rechts drehen",
    orbitUp: "Nach oben drehen",
    orbitDown: "Nach unten drehen",
    zoomIn: "Vergrößern",
    zoomOut: "Verkleinern",
    reset: "Kamera zurücksetzen",
    fullscreen: "Vollbild",
    exitFullscreen: "Vollbild verlassen",
    inspect: "Roboter prüfen",
    select: "Roboter auswählen",
    focus: "Kamera auf Roboter richten",
    joints: "Live-Gelenkzustand",
    position: "Position",
    velocity: "Geschwindigkeit",
    joint: "Gelenk",
    provenance:
      "Simulierte Diagnosebewegung · nativ gerenderte Bilder · keine Befehle an physische Roboter",
    age: "Bildalter",
    frame: "Bild",
    fps: "Bilder/s",
    overview: "Fabrikübersicht",
    replay: "Aufgezeichneter Lauf",
  },
  fr: {
    busy: "Le simulateur est occupé. Arrêtez l’autre vue en direct ou l’entraînement, puis réessayez.",
    expired:
      "La session en direct a expiré. Démarrez une nouvelle vue en direct.",
    stopped: "Vue en direct arrêtée",
    recordedJoints: "Dernier état articulaire reçu",
    start: "Démarrer la simulation en direct",
    stop: "Arrêter la vue en direct",
    starting: "Démarrage d’Isaac Sim…",
    warming:
      "Le GPU prépare la scène. La première image peut prendre une minute.",
    live: "Isaac Sim en direct",
    recorded: "Aperçu enregistré",
    stale: "Flux interrompu · dernière image",
    failed:
      "La vue en direct est indisponible. Réessayez lorsque le simulateur est prêt.",
    cameraError: "Le déplacement de la caméra a échoué. Réessayez.",
    stopError:
      "L’arrêt n’a pas été confirmé. La session expirera automatiquement.",
    hint: "Glisser pour tourner · Maj et glisser pour déplacer · Défiler pour zoomer · Cliquer sur un robot pour l’inspecter",
    keys: "Les flèches tournent ; Maj et flèches déplacent ; + et − zooment ; R réinitialise la caméra.",
    orbitLeft: "Tourner à gauche",
    orbitRight: "Tourner à droite",
    orbitUp: "Tourner vers le haut",
    orbitDown: "Tourner vers le bas",
    zoomIn: "Zoom avant",
    zoomOut: "Zoom arrière",
    reset: "Réinitialiser la caméra",
    fullscreen: "Plein écran",
    exitFullscreen: "Quitter le plein écran",
    inspect: "Inspecter le robot",
    select: "Sélectionner un robot",
    focus: "Centrer la caméra sur le robot",
    joints: "État articulaire en direct",
    position: "Position",
    velocity: "Vitesse",
    joint: "Articulation",
    provenance:
      "Mouvement diagnostique simulé · images natives · aucune commande de robot physique",
    age: "Âge de l’image",
    frame: "Image",
    fps: "images/s",
    overview: "Vue d’ensemble de l’usine",
    replay: "Exécution enregistrée",
  },
} as const;
export type LiveLabels = (typeof labels)["en"] extends infer T
  ? { [K in keyof T]: string }
  : never;
export const liveLabels = (locale: Locale): LiveLabels => labels[locale];
