import type { Slide } from "./content";
export const de: Slide[] = [
  {
    label: "KIVOF / PHYSISCHE KI",
    title: "Jeder Lauf.\nEin besserer nächster Schritt.",
    body: "Der Nachweis-Arbeitsbereich für eine simulierte Käsesortierlinie.",
    points: ["HPE & NVIDIA · Genf 2026", "Cheese Factory · Harness Forge"],
    note: "Software-Demonstrator. Physische Autonomie und Inbetriebnahme benötigen separate Validierung.",
    visual: "cell",
  },
  {
    label: "01 / DAS PROBLEM",
    title: "Ein Roboter scheitert.\nDer Kontext zerfällt.",
    body: "Video, Kraft, Entscheidungen und Ergebnisse liegen oft getrennt. Verbesserung beginnt mit der Rekonstruktion.",
    points: [
      "Welche Beobachtung war verlässlich?",
      "Was hat der Controller wirklich ausgeführt?",
      "Wurde die Aufgabe unabhängig geprüft?",
    ],
    note: "Produkthypothese aus der bereitgestellten Challenge; Kundennachfrage ist noch nicht validiert.",
    visual: "loop",
  },
  {
    label: "02 / DER ABLAUF",
    title: "Von der Beobachtung\nzur geprüften Verbesserung.",
    body: "Kivof verbindet Lauf, Sensornachweise, begrenzte Evaluation und Annotation.",
    points: [
      "Herkunft und Qualität prüfen",
      "Eine belegte visuelle Erklärung anfordern",
      "Fehler für die Prüfung bewahren",
    ],
    note: "Die Oberfläche trennt aufgezeichnete Simulation, verbundenen Transport und nicht verfügbare Hardware.",
    visual: "loop",
  },
  {
    label: "03 / CHEESE FACTORY",
    title: "Ein Käse.\nDer richtige Behälter.\nEine prüfbare Entscheidung.",
    body: "Eine Kamera beobachtet das Förderband. Die Klassifikation wählt den Behälter. Ein begrenzter Sortierversuch zeichnet Ablage und Ablehnungen auf.",
    points: [
      "Klassifizieren und im Zielbehälter ablegen",
      "Unsichere oder veraltete Beobachtungen zurückhalten",
      "Ablagefehler zur Prüfung bewahren",
    ],
    note: "Deterministische Sortiersimulation und native Isaac-Versuche tragen getrennte Herkunftsangaben. Simulation ist keine physische Validierung.",
    visual: "proof",
  },
  {
    label: "04 / DER NACHWEIS",
    title: "Eine Antwort,\ndie sich prüfen lässt.",
    body: "Text, Sprache, Tabellen, Grafiken und Diagramme teilen ein Gespräch mit Quellen und Anbieterstatus.",
    points: [
      "Modellauswahl über das Core-Gateway",
      "Generierte Illustrationen klar gekennzeichnet",
      "Annotationen behalten die Laufidentität",
    ],
    note: "Eine Modellerklärung ist keine Sicherheitsfreigabe. Zusammenfassungen zeigen beobachtbare Arbeit, keine privaten Denkprozesse.",
    visual: "layers",
  },
  {
    label: "05 / DAS SYSTEM",
    title: "Physische Freigabe\nbleibt lokal.",
    body: "Der Browser verbindet Rust-Dienste und Orchestrierung. Modell-Zugangsdaten bleiben im Inferenzkern.",
    points: [
      "Web → authentifiziertes Backend",
      "OpenClaw → Rust-Inferenzkern",
      "Roboterlaufzeit → lokaler Controller",
    ],
    note: "Ein Chat-Vorschlag wird niemals direkt zu einem Motorbefehl.",
    visual: "layers",
  },
  {
    label: "06 / DER PILOT",
    title: "Mit einer Zelle starten.\nVerbesserung messen.",
    body: "Ein Industrieteam und eine freigegebene Aufgabe. Diagnosequalität, Annotationen und Wiederholbarkeit evaluieren.",
    points: [
      "Nutzer: Robotik- und Betriebsteams",
      "Käuferhypothese: Fertigungsengineering",
      "Diagnosezeit und zurückgehaltene Aufgaben messen",
    ],
    note: "Kommerzielle Hypothese. Keine Kunden, Umsätze, Marktgröße, Einsparungen oder Zertifizierung werden behauptet.",
    visual: "loop",
  },
  {
    label: "07 / NÄCHSTE VALIDIERUNG",
    title: "Bringen Sie einen schwierigen Lauf.\nPrüfen wir die Nachweise.",
    body: "Arbeitsbereich öffnen, Variation ausführen, Verifizierung verfolgen und Beobachtungen hinterfragen.",
    points: [
      "Jeden fehlgeschlagenen Versuch prüfen",
      "Kompatible Hardware verbinden und einrichten",
      "Eine zurückgehaltene physische Aufgabe evaluieren",
    ],
    note: "Kivof · Cheese Factory · Entwickelt von JO · 24. September 2026",
    visual: "cell",
  },
];
