import type { DeckCopy, DeckLabels } from "./types";
export const deLabels: DeckLabels = {
  startDemo: "Neue Demo starten",
  loadDemo: "Arbeitsbereich laden",
  loadReplay: "Aufzeichnung laden",
  loading: "Wird geöffnet…",
  demoError:
    "Die Demo konnte nicht geöffnet werden. Erneut versuchen oder in neuem Tab öffnen.",
  open: "In neuem Tab öffnen",
  reload: "Demo neu laden",
  mediaNote:
    "Wenn die eingebettete Ansicht nicht verfügbar ist, in einem neuen Tab öffnen.",
  inactiveMedia: "Diese Folie öffnen, um abzuspielen oder zu erkunden.",
  recording: "Aufgezeichnete Demonstration",
  interactive: "Interaktive Demo",
  jump: "Folie wählen",
  keyboard: "← → zum Navigieren",
  modelTask: "Modellaufgabe",
  correctImages: "Richtige Bilder",
  accuracy: "Genauigkeit",
  macroF1: "Macro-F1",
  cheeseType: "Käsesorte",
  destination: "Zielbehälter",
  bins: ["Hart", "Halbhart", "Weich", "Frisch", "Blau"],
  source: "Bereitgestelltes Projektbild",
};
export const de: DeckCopy = {
  hero: {
    label: "HPE × NVIDIA / GENF",
    title: "Physical AI.\nCheese Factory.",
    body: "Kamerageführte Sortierung. Nachweise zum Erkunden.",
    points: ["Eine simulierte Fabrik", "Jede Entscheidung aus Betreibersicht"],
    note: "Cheese Factory × Kivof · September 2026",
  },
  task: {
    label: "01 / DIE AUFGABE",
    title: "Elf Käsesorten.\nFünf Ziele.",
    body: "Eine klare Sortierentscheidung beginnt beim Produkt vor der Kamera.",
    points: [
      "Hartkäse · Emmentaler",
      "Schnittkäse · Raclette",
      "Weichkäse · Ziegenweichkäse · Schmelzkäse",
      "Frischkäse · Hüttenkäse · Frischkäsecreme",
      "Blauschimmelkäse",
    ],
    note: "Unsichere Produkte und Fremdobjekte nehmen einen separaten Ausschleusweg.",
  },
  capture: {
    label: "01 / VON DER KAMERA ZUM GRIFF",
    title: "Erfassen. Einordnen.\nPrüfen. Ablegen.",
    body: "Bild und Position bleiben mit der daraus entstandenen Entscheidung verbunden.",
    points: [
      "Erfassen\nBild und Position",
      "Einordnen\nKäsesorte und Behälter",
      "Prüfen\nProdukt, Bild und Konfidenz",
      "Greifen und ablegen\nFranka-Bewegung in Isaac Sim",
    ],
    note: "Bei unsicheren oder widersprüchlichen Nachweisen hält der Arm an.",
  },
  training: {
    label: "01 / TRAINING",
    title: "Von annotierten Bildern\nzum Sortiermodell.",
    body: "ConvNeXt-Training in PyTorch mit 384 px großen Modelleingaben.",
    points: ["Annotierte Freisteller", "Späterer Replicator-Prototyp"],
    note: "Verwandte Ansichten bleiben im selben Datensplit. Das Replicator-Raster ist ein Prototyp, kein Produktionstrainingsdatensatz.",
  },
  clearance: {
    label: "01 / DIE ROBOTERZELLE",
    title: "Raum für\nBewegung schaffen.",
    body: "Freiraum und Kollisionsgeometrie gehören zur Aufgabenplanung.",
    points: [
      "Stützen außerhalb der nominalen Reichweite",
      "Portalgeometrie in Physik und Planung",
    ],
    note: "Bereitgestellter Teamcheck: 10 Griffe + 1 Ausschleusung mit vorgegebenen Labels. Prüft Bewegung, nicht Erkennung.",
  },
  scores: {
    label: "01 / ZURÜCKGEHALTENE BILDER",
    title: "Erkennung mit\nunbekannten Bildern messen.",
    body: "Zwei Modellaufgaben. Zwei getrennte Bildtestsätze.",
    points: [],
    note: "Ergebnisse der bereitgestellten Version 9. Macro-F1 gewichtet Klassen gleich; die Werte belegen keine Zuverlässigkeit der gesamten Fabrik.",
  },
  outcomes: {
    label: "01 / DER FABRIKLAUF",
    title: "Erkennung bleibt\ndie größere Hürde.",
    body: "Ein Lauf mit elf Produkten macht den Unterschied sichtbar.",
    points: [
      "Modellentscheidungen\n3 Ablagen + 1 Ausschleusung",
      "Vorgegebene Labels\nReine Bewegungsprüfung",
    ],
    note: "10 Käseprodukte + 1 Fremdobjekt. Alle vier versuchten Griffe wurden abgeschlossen. Lauf aus der bereitgestellten Version 9.",
  },
  video1: {
    label: "02 / FILM 01",
    title: "Die Fabrik\nin Bewegung.",
    body: "Die bereitgestellte Demonstration im eigenen Bild.",
    points: [],
    note: "Aufgezeichnetes Video · Wiedergabe per Klick starten.",
  },
  operator: {
    label: "02 / DER BETREIBER",
    title: "Sehen, warum\nder Arm stoppt.",
    body: "Kamerabild. Widersprüchliche Vorhersagen. Ein sichtbarer Haltegrund.",
    points: [
      "Entscheidung und Quelle zusammenhalten",
      "Unsicherheit vor dem nächsten Griff prüfen",
    ],
    note: "Bereitgestellte Dashboard-Aufnahme aus einem separaten Check.",
  },
  replay: {
    label: "02 / AUFZEICHNUNG ERKUNDEN",
    title: "Zeitpunkt wählen.\nBlickwinkel verändern.",
    body: "Die aufgezeichnete Cheese-Factory-Szene erkunden.",
    points: [],
    note: "adiy.ch/cheese · Interaktive Aufzeichnung; Betrachter benötigen keine laufende Isaac-Sitzung.",
  },
  video2: {
    label: "02 / FILM 02",
    title: "Genauer\nhinsehen.",
    body: "Eine zweite bereitgestellte Demonstration.",
    points: [],
    note: "Aufgezeichnetes Video · Wiedergabe per Klick starten.",
  },
  export: {
    label: "02 / DIE SZENE TEILEN",
    title: "Einmal aufzeichnen.\nIm Browser erkunden.",
    body: "Isaac Web Exporter macht eine Szene für andere Zeitpunkte und Perspektiven zugänglich.",
    points: [
      "Erfassen\nKompatible Bewegung in USD",
      "Bündeln\nGLB-Geometrie, Bewegung und JSON",
      "Veröffentlichen\nThree.js / WebGL",
    ],
    note: "Die Fabrik nutzt einen projektspezifischen Aufnahmeadapter. Browserwiedergabe ist aufgezeichnetes 3D, keine Simulatorsteuerung.",
  },
  workspace: {
    label: "03 / KIVOF",
    title: "Ein Lauf ist\nmehr als ein Video.",
    body: "Beobachtungen, Erklärungen und geprüfte Labels in einem Arbeitsbereich verbinden.",
    points: [
      "Nachweise prüfen",
      "Das Ergebnis verstehen",
      "Die nächste Verbesserung nachvollziehbar halten",
    ],
    note: "Aufgezeichnetes Kivof-Isaac-Inspektionsbild · Vor dem Griff.",
  },
  workflow: {
    label: "03 / DER PRÜFKREISLAUF",
    title: "Vom Lauf zum\ngeprüften nächsten Schritt.",
    body: "Erfolge und Fehler bleiben für die Untersuchung erhalten.",
    points: [
      "Beobachten\nLauf- und Sensornachweise",
      "Verstehen\nBelegte Erklärungen",
      "Bewerten\nBegrenzte Aufgabenergebnisse",
      "Verbessern\nGeprüfte Annotation",
    ],
    note: "Ursprüngliche Vorhersagen bleiben bei menschlichen Labelkorrekturen erhalten.",
  },
  demo: {
    label: "03 / KIVOF ÖFFNEN",
    title: "Den Arbeitsbereich\nerkunden.",
    body: "Ein Szenario ausführen, Nachweise prüfen und ein Label korrigieren.",
    points: [],
    note: "Live-Anwendung. Fabrikversuche bleiben simuliert; physische Bewegung ist nicht autorisiert.",
  },
  boundary: {
    label: "03 / DIE STEUERUNGSGRENZE",
    title: "Zentral erklären.\nLokal handeln.",
    body: "Das Gespräch des Betreibers bleibt von der Motorbefugnis getrennt.",
    points: [
      "Browser-Arbeitsbereich\nNachweise und Diskussion",
      "Rust-Dienste + OpenClaw\nAuthentifizierte Orchestrierung",
      "Lokaler Controller\nAusführungsbefugnis",
    ],
    note: "Eine Erklärung ist weder Sicherheitsfreigabe noch Motorbefehl.",
  },
  native: {
    label: "03 / NATIVE SIMULATION",
    title: "Physik mit\nprüfbaren Nachweisen.",
    body: "Ein aufgezeichnetes Isaac-Kamerabild begleitet gemessene Roboterbewegung und Ablage.",
    points: [
      "Aufgezeichnete Kamera- und Gelenkdaten",
      "Gemessene Freigabe, Anhebung und Behälterdistanz",
    ],
    note: "Nativer Kivof-Check: farbiger starrer Körper und experimentelle Farberkennung. Kein trainierter Käseklassifikator und kein physischer Robotereinsatz in diesem Check.",
  },
  video3: {
    label: "03 / FILM 03",
    title: "Vom Lauf\nzu seinen Nachweisen.",
    body: "Die dritte bereitgestellte Demonstration.",
    points: [],
    note: "Aufgezeichnetes Video · Wiedergabe per Klick starten.",
  },
  exporterIntro: {
    label: "02 / ISAAC WEB EXPORTER",
    title: "Aufgezeichnete Szene.\nInteraktive Website.",
    body: "Die Szene teilen, ohne dass Betrachter Isaac installieren müssen.",
    points: ["Zeitpunkt wählen", "Kamerawinkel wählen"],
    note: "Aufgezeichnete 3D-Wiedergabe. Betrachter steuern den Simulator nicht.",
  },
  viewer: {
    label: "02 / DER VIEWER",
    title: "Einen Moment prüfen.\nEin Objekt prüfen.",
    body: "Die Aufnahme pausieren und das Wesentliche erkunden.",
    points: [
      "Ein Bild weitergehen",
      "Ein Glied fokussieren",
      "Ein Objekt isolieren",
    ],
    note: "Bereitgestellte Isaac-Web-Exporter-Oberfläche. Aufgezeichnete Szene bei 35 Sekunden.",
  },
  formats: {
    label: "02 / DREI FORMEN DES TEILENS",
    title: "Video. Live-Isaac.\nBrowserwiedergabe.",
    body: "Das passende Format für die Prüfung wählen.",
    points: [
      "Video\nAufgezeichnete Kameraansicht\nWiedergabezeit wählen\nVideodatei teilen",
      "Live-Isaac\nInteraktive Live-Sitzung\nSimulator bedienen\nHost weiter betreiben",
      "Webexport\nAufgezeichnete 3D-Szene\nZeit und Kamera wählen\nStatische Dateien veröffentlichen",
    ],
    note: "Browserwiedergabe bietet einen anderen Blickwinkel ohne laufende Isaac-Sitzung.",
  },
  replayInvite: {
    label: "02 / FABRIKAUFZEICHNUNG TESTEN",
    title: "Die Fabrik,\nbereit zum Erkunden.",
    body: "Einen Griff pausieren. Den Blickwinkel ändern.",
    points: ["adiy.ch/cheese", "Isaac Web Exporter"],
    note: "Aufgezeichnete Cheese-Factory-Szene · gr9aditya/isaac-web-exporter.",
  },
  closing: {
    label: "PHYSICAL AI / CHEESE FACTORY",
    title: "Einen Griff pausieren.\nEine Frage stellen.",
    body: "Die Nachweise gemeinsam erkunden.",
    points: ["kivof.com", "adiy.ch/cheese"],
    note: "Cheese Factory × Kivof · HPE & NVIDIA Hackathon · Genf",
  },
};
