import type { DeckCopy, DeckLabels } from "./types";
export const enLabels: DeckLabels = {
  startDemo: "Start a new demo",
  loadDemo: "Load workspace",
  loadReplay: "Load recorded scene",
  loading: "Opening…",
  demoError: "The demo could not be opened. Retry or open it in a new tab.",
  open: "Open in a new tab",
  reload: "Reload demo",
  mediaNote: "If the embedded view is unavailable, open it in a new tab.",
  inactiveMedia: "Open this slide to play or explore.",
  recording: "Recorded demonstration",
  interactive: "Interactive demo",
  jump: "Choose a slide",
  keyboard: "← → to navigate",
  modelTask: "Model task",
  correctImages: "Correct images",
  accuracy: "Accuracy",
  macroF1: "Macro-F1",
  cheeseType: "Cheese type",
  destination: "Destination bin",
  bins: ["Hard", "Semi-hard", "Soft", "Fresh", "Blue"],
  source: "Supplied project image",
};
export const en: DeckCopy = {
  hero: {
    label: "HPE × NVIDIA / GENEVA",
    title: "Physical AI.\nCheese Factory.",
    body: "Camera-guided sorting. Evidence you can explore.",
    points: ["A simulated factory", "An operator’s view of every decision"],
    note: "Cheese Factory × Kivof · September 2026",
  },
  task: {
    label: "01 / THE TASK",
    title: "Eleven cheese types.\nFive destinations.",
    body: "A clear sorting decision starts with the item in front of the camera.",
    points: [
      "Hard cheese · Emmental",
      "Semi-hard cheese · Raclette",
      "Soft cheese · Soft goat cheese · Processed cheese",
      "Fresh cheese · Cottage cheese · Cream cheese",
      "Blue mould cheese",
    ],
    note: "Uncertain and non-cheese items follow a separate reject path.",
  },
  capture: {
    label: "01 / CAMERA TO PICK",
    title: "Observe. Classify.\nCheck. Place.",
    body: "The decision travels with the image and position that produced it.",
    points: [
      "Capture\nImage and position",
      "Classify\nCheese type and bin",
      "Check\nItem, frame and confidence",
      "Pick + place\nFranka motion in Isaac Sim",
    ],
    note: "Uncertain or conflicting evidence holds the arm.",
  },
  training: {
    label: "01 / TRAINING",
    title: "From labeled images\nto a sorting model.",
    body: "ConvNeXt training in PyTorch, with a 384 px model input.",
    points: ["Labeled cutouts", "Later Replicator prototype"],
    note: "Related views stay in one data split. The Replicator grid is a prototype, not production training data.",
  },
  clearance: {
    label: "01 / THE ROBOT CELL",
    title: "Give the arm\nroom to move.",
    body: "Clearance and collision geometry belong in the task design.",
    points: [
      "Posts outside nominal reach",
      "Gantry geometry in physics and planning",
    ],
    note: "Supplied team check: 10 picks + 1 reject completed with scripted labels. This tests motion, not recognition.",
  },
  scores: {
    label: "01 / HELD-OUT IMAGES",
    title: "Measure recognition\non unseen images.",
    body: "Two model tasks. Two separate image-test sets.",
    points: [],
    note: "Supplied Version 9 results. Macro-F1 weighs classes equally; these scores do not establish full-factory reliability.",
  },
  outcomes: {
    label: "01 / THE FACTORY RUN",
    title: "Recognition is still\nthe harder problem.",
    body: "An eleven-item run makes the gap visible.",
    points: [
      "Model decisions\n3 placements + 1 reject",
      "Scripted labels\nMotion check only",
    ],
    note: "10 cheese items + 1 non-cheese item. All four attempted picks completed. Supplied Version 9 run.",
  },
  video1: {
    label: "02 / FILM 01",
    title: "Watch the\nfactory run.",
    body: "The supplied demonstration, in its own frame.",
    points: [],
    note: "Recorded video · Playback starts when you press play.",
  },
  operator: {
    label: "02 / THE OPERATOR",
    title: "See why\nthe arm stops.",
    body: "Captured image. Conflicting predictions. A visible hold reason.",
    points: [
      "Keep the decision with its source",
      "Inspect uncertainty before another pick",
    ],
    note: "Supplied dashboard capture from a separate check.",
  },
  replay: {
    label: "02 / EXPLORE THE REPLAY",
    title: "Choose the moment.\nChange the viewpoint.",
    body: "Explore the recorded Cheese Factory scene.",
    points: [],
    note: "adiy.ch/cheese · Interactive recorded scene; no live Isaac session is required for the viewer.",
  },
  video2: {
    label: "02 / FILM 02",
    title: "Take a\ncloser look.",
    body: "A second supplied demonstration.",
    points: [],
    note: "Recorded video · Playback starts when you press play.",
  },
  export: {
    label: "02 / SHARE THE SCENE",
    title: "Record once.\nExplore in the browser.",
    body: "Isaac Web Exporter packages a scene for another time and viewpoint.",
    points: [
      "Capture\nCompatible motion in USD",
      "Package\nGLB geometry, motion and JSON",
      "Publish\nThree.js / WebGL",
    ],
    note: "The factory uses a project-specific capture adapter. Browser replay is recorded 3D, not simulator control.",
  },
  workspace: {
    label: "03 / KIVOF",
    title: "A run is more\nthan a video.",
    body: "Bring observations, explanations and reviewed labels into one workspace.",
    points: [
      "Inspect the evidence",
      "Understand the outcome",
      "Keep the next improvement traceable",
    ],
    note: "Recorded Kivof Isaac inspection image · Before the pick.",
  },
  workflow: {
    label: "03 / THE REVIEW LOOP",
    title: "Turn a run into\na reviewed next step.",
    body: "Keep both success and failure available for inspection.",
    points: [
      "Observe\nRun and sensor evidence",
      "Understand\nGrounded explanations",
      "Evaluate\nBounded task outcomes",
      "Improve\nReviewed annotation",
    ],
    note: "Original predictions remain preserved when a human corrects a label.",
  },
  demo: {
    label: "03 / OPEN KIVOF",
    title: "Explore the\nworkspace.",
    body: "Run a scenario, inspect its evidence and review a label.",
    points: [],
    note: "A live application. Factory trials remain simulated; physical motion is not authorized.",
  },
  boundary: {
    label: "03 / THE CONTROL BOUNDARY",
    title: "Explain centrally.\nAct locally.",
    body: "The operator’s conversation stays separate from motor authority.",
    points: [
      "Browser workspace\nEvidence and discussion",
      "Rust services + OpenClaw\nAuthenticated orchestration",
      "Local controller\nExecution authority",
    ],
    note: "An explanation is not a safety approval or a motor command.",
  },
  native: {
    label: "03 / NATIVE SIMULATION",
    title: "Physics, with\ninspectable evidence.",
    body: "A recorded Isaac camera frame accompanies measured robot motion and placement.",
    points: [
      "Recorded camera and joint samples",
      "Measured release, lift and bin distance",
    ],
    note: "Kivof native check: colored rigid proxy and development color perception. No trained cheese classifier or physical robot execution in this check.",
  },
  video3: {
    label: "03 / FILM 03",
    title: "From a run\nto its evidence.",
    body: "The third supplied demonstration.",
    points: [],
    note: "Recorded video · Playback starts when you press play.",
  },
  exporterIntro: {
    label: "02 / ISAAC WEB EXPORTER",
    title: "A recorded scene.\nAn interactive website.",
    body: "Share the scene without asking the viewer to install Isaac.",
    points: ["Choose the time", "Choose the camera angle"],
    note: "Recorded 3D playback. The viewer does not operate the simulator.",
  },
  viewer: {
    label: "02 / THE VIEWER",
    title: "Inspect a moment.\nInspect an object.",
    body: "Pause the recording, then explore what matters.",
    points: ["Step one frame", "Focus on a link", "Isolate an item"],
    note: "Supplied Isaac Web Exporter interface. Recorded scene at 35 seconds.",
  },
  formats: {
    label: "02 / THREE WAYS TO SHARE",
    title: "Video. Live Isaac.\nBrowser replay.",
    body: "Choose the format that fits the review.",
    points: [
      "Video\nRecorded camera view\nChoose playback time\nShare a video file",
      "Live Isaac\nInteractive live session\nOperate the simulator\nKeep the host running",
      "Web export\nRecorded 3D scene\nChoose time and camera\nPublish static files",
    ],
    note: "Browser replay adds another camera angle without keeping Isaac live.",
  },
  replayInvite: {
    label: "02 / TRY THE FACTORY REPLAY",
    title: "The factory,\nready to explore.",
    body: "Pause a pick. Change the view.",
    points: ["adiy.ch/cheese", "Isaac Web Exporter"],
    note: "Recorded Cheese Factory scene · gr9aditya/isaac-web-exporter.",
  },
  closing: {
    label: "PHYSICAL AI / CHEESE FACTORY",
    title: "Pause a pick.\nAsk a question.",
    body: "Let’s explore the evidence together.",
    points: ["kivof.com", "adiy.ch/cheese"],
    note: "Cheese Factory × Kivof · HPE & NVIDIA Hackathon · Geneva",
  },
};
