import type { DeckCopy, DeckLabels } from "./types";
export const esLabels: DeckLabels = {
  startDemo: "Iniciar una demo nueva",
  loadDemo: "Cargar espacio de trabajo",
  loadReplay: "Cargar escena grabada",
  loading: "Abriendo…",
  demoError:
    "No se pudo abrir la demo. Reintenta o ábrela en una pestaña nueva.",
  open: "Abrir en una pestaña nueva",
  reload: "Recargar demo",
  mediaNote:
    "Si la vista integrada no está disponible, ábrela en una pestaña nueva.",
  inactiveMedia: "Abre esta diapositiva para reproducir o explorar.",
  recording: "Demostración grabada",
  interactive: "Demo interactiva",
  jump: "Elegir diapositiva",
  keyboard: "← → para navegar",
  modelTask: "Tarea del modelo",
  correctImages: "Imágenes correctas",
  accuracy: "Exactitud",
  macroF1: "Macro-F1",
  cheeseType: "Tipo de queso",
  destination: "Contenedor de destino",
  bins: ["Duro", "Semiduro", "Blando", "Fresco", "Azul"],
  source: "Imagen del proyecto facilitada",
};
export const es: DeckCopy = {
  hero: {
    label: "HPE × NVIDIA / GINEBRA",
    title: "IA física.\nCheese Factory.",
    body: "Clasificación guiada por cámara. Evidencias que puedes explorar.",
    points: ["Una fábrica simulada", "Cada decisión, a la vista del operador"],
    note: "Cheese Factory × Kivof · Septiembre de 2026",
  },
  task: {
    label: "01 / LA TAREA",
    title: "Once tipos de queso.\nCinco destinos.",
    body: "Una decisión de clasificación clara comienza con el producto ante la cámara.",
    points: [
      "Queso duro · Emmental",
      "Queso semiduro · Raclette",
      "Queso blando · Cabra blando · Queso fundido",
      "Queso fresco · Cottage · Queso crema",
      "Queso azul",
    ],
    note: "Los productos inciertos o que no son queso siguen una vía de rechazo separada.",
  },
  capture: {
    label: "01 / DE LA CÁMARA AL AGARRE",
    title: "Observar. Clasificar.\nComprobar. Colocar.",
    body: "La decisión conserva la imagen y la posición que la originaron.",
    points: [
      "Capturar\nImagen y posición",
      "Clasificar\nTipo de queso y destino",
      "Comprobar\nProducto, imagen y confianza",
      "Agarrar y colocar\nMovimiento Franka en Isaac Sim",
    ],
    note: "Las evidencias inciertas o contradictorias detienen el brazo.",
  },
  training: {
    label: "01 / ENTRENAMIENTO",
    title: "De imágenes etiquetadas\na un modelo de clasificación.",
    body: "Entrenamiento ConvNeXt en PyTorch, con imágenes de entrada de 384 px.",
    points: ["Recortes etiquetados", "Prototipo posterior de Replicator"],
    note: "Las vistas relacionadas permanecen en la misma partición. La cuadrícula de Replicator es un prototipo, no datos de entrenamiento de producción.",
  },
  clearance: {
    label: "01 / LA CELDA ROBÓTICA",
    title: "Dar espacio\nal movimiento.",
    body: "El espacio libre y la geometría de colisión forman parte del diseño de la tarea.",
    points: [
      "Postes fuera del alcance nominal",
      "Geometría del pórtico en física y planificación",
    ],
    note: "Comprobación del equipo: 10 agarres + 1 rechazo con etiquetas predefinidas. Evalúa movimiento, no reconocimiento.",
  },
  scores: {
    label: "01 / IMÁGENES RESERVADAS",
    title: "Medir el reconocimiento\ncon imágenes nuevas.",
    body: "Dos tareas del modelo. Dos conjuntos de prueba distintos.",
    points: [],
    note: "Resultados de la versión 9 facilitada. Macro-F1 pondera cada clase por igual; estas cifras no establecen la fiabilidad de toda la fábrica.",
  },
  outcomes: {
    label: "01 / LA PRUEBA EN FÁBRICA",
    title: "Reconocer sigue siendo\nel reto más difícil.",
    body: "Una prueba de once productos hace visible la diferencia.",
    points: [
      "Decisiones del modelo\n3 colocaciones + 1 rechazo",
      "Etiquetas predefinidas\nSolo prueba de movimiento",
    ],
    note: "10 quesos + 1 producto no quesero. Los cuatro agarres intentados se completaron. Prueba de la versión 9 facilitada.",
  },
  video1: {
    label: "02 / VÍDEO 01",
    title: "Ver la fábrica\nen acción.",
    body: "La demostración facilitada, en su propio encuadre.",
    points: [],
    note: "Vídeo grabado · Pulsa reproducir para comenzar.",
  },
  operator: {
    label: "02 / EL OPERADOR",
    title: "Ver por qué\nse detiene el brazo.",
    body: "Imagen capturada. Predicciones contradictorias. Motivo de espera visible.",
    points: [
      "Conservar la decisión con su fuente",
      "Examinar la incertidumbre antes de otro agarre",
    ],
    note: "Captura del panel facilitada, procedente de una comprobación separada.",
  },
  replay: {
    label: "02 / EXPLORAR LA REPRODUCCIÓN",
    title: "Elegir el momento.\nCambiar el punto de vista.",
    body: "Explora la escena grabada de Cheese Factory.",
    points: [],
    note: "adiy.ch/cheese · Escena grabada interactiva; el espectador no necesita una sesión Isaac activa.",
  },
  video2: {
    label: "02 / VÍDEO 02",
    title: "Mirar\nmás de cerca.",
    body: "Una segunda demostración facilitada.",
    points: [],
    note: "Vídeo grabado · Pulsa reproducir para comenzar.",
  },
  export: {
    label: "02 / COMPARTIR LA ESCENA",
    title: "Grabar una vez.\nExplorar en el navegador.",
    body: "Isaac Web Exporter prepara una escena para explorar otros momentos y perspectivas.",
    points: [
      "Capturar\nMovimiento compatible en USD",
      "Empaquetar\nGeometría GLB, movimiento y JSON",
      "Publicar\nThree.js / WebGL",
    ],
    note: "La fábrica utiliza un adaptador de captura específico. La reproducción web es 3D grabado, no control del simulador.",
  },
  workspace: {
    label: "03 / KIVOF",
    title: "Una ejecución es\nmás que un vídeo.",
    body: "Reúne observaciones, explicaciones y etiquetas revisadas en un solo espacio.",
    points: [
      "Examinar las evidencias",
      "Comprender el resultado",
      "Mantener trazable la siguiente mejora",
    ],
    note: "Imagen de inspección Isaac de Kivof grabada · Antes del agarre.",
  },
  workflow: {
    label: "03 / EL CICLO DE REVISIÓN",
    title: "De una ejecución\na un siguiente paso revisado.",
    body: "Conserva tanto los éxitos como los fallos para examinarlos.",
    points: [
      "Observar\nEjecución y sensores",
      "Comprender\nExplicaciones fundamentadas",
      "Evaluar\nResultados de tareas acotadas",
      "Mejorar\nAnotación revisada",
    ],
    note: "Las predicciones originales se conservan cuando una persona corrige una etiqueta.",
  },
  demo: {
    label: "03 / ABRIR KIVOF",
    title: "Explorar\nel espacio de trabajo.",
    body: "Ejecuta un escenario, examina sus evidencias y revisa una etiqueta.",
    points: [],
    note: "Aplicación en vivo. Las pruebas de fábrica siguen siendo simuladas; no se autoriza movimiento físico.",
  },
  boundary: {
    label: "03 / EL LÍMITE DE CONTROL",
    title: "Explicar de forma central.\nActuar de forma local.",
    body: "La conversación del operador permanece separada de la autoridad sobre los motores.",
    points: [
      "Espacio web\nEvidencias y conversación",
      "Servicios Rust + OpenClaw\nOrquestación autenticada",
      "Controlador local\nAutoridad de ejecución",
    ],
    note: "Una explicación no es una aprobación de seguridad ni una orden de movimiento.",
  },
  native: {
    label: "03 / SIMULACIÓN NATIVA",
    title: "Física con\nevidencias examinables.",
    body: "Una imagen Isaac grabada acompaña al movimiento medido del robot y a su colocación.",
    points: [
      "Cámara y muestras articulares registradas",
      "Apertura, elevación y distancia al contenedor medidas",
    ],
    note: "Prueba nativa Kivof: objeto rígido de color y percepción experimental por color. Sin clasificador de queso entrenado ni robot físico en esta prueba.",
  },
  video3: {
    label: "03 / VÍDEO 03",
    title: "De la ejecución\na sus evidencias.",
    body: "La tercera demostración facilitada.",
    points: [],
    note: "Vídeo grabado · Pulsa reproducir para comenzar.",
  },
  exporterIntro: {
    label: "02 / ISAAC WEB EXPORTER",
    title: "Una escena grabada.\nUn sitio interactivo.",
    body: "Comparte la escena sin pedir al espectador que instale Isaac.",
    points: ["Elegir el momento", "Elegir el ángulo de cámara"],
    note: "Reproducción 3D grabada. El espectador no controla el simulador.",
  },
  viewer: {
    label: "02 / EL VISOR",
    title: "Examinar un momento.\nExaminar un objeto.",
    body: "Pausa la grabación y explora lo que importa.",
    points: [
      "Avanzar un fotograma",
      "Enfocar un eslabón",
      "Aislar un producto",
    ],
    note: "Interfaz de Isaac Web Exporter facilitada. Escena grabada en el segundo 35.",
  },
  formats: {
    label: "02 / TRES FORMAS DE COMPARTIR",
    title: "Vídeo. Isaac en vivo.\nReproducción web.",
    body: "Elige el formato adecuado para la revisión.",
    points: [
      "Vídeo\nVista de cámara grabada\nElegir el momento\nCompartir un archivo",
      "Isaac en vivo\nSesión interactiva en directo\nControlar el simulador\nMantener el servidor activo",
      "Exportación web\nEscena 3D grabada\nElegir tiempo y cámara\nPublicar archivos estáticos",
    ],
    note: "La reproducción web ofrece otro ángulo sin mantener Isaac en funcionamiento.",
  },
  replayInvite: {
    label: "02 / PROBAR LA REPRODUCCIÓN",
    title: "La fábrica,\nlista para explorar.",
    body: "Pausa un agarre. Cambia la perspectiva.",
    points: ["adiy.ch/cheese", "Isaac Web Exporter"],
    note: "Escena Cheese Factory grabada · gr9aditya/isaac-web-exporter.",
  },
  closing: {
    label: "IA FÍSICA / CHEESE FACTORY",
    title: "Pausar un agarre.\nHacer una pregunta.",
    body: "Exploremos juntos las evidencias.",
    points: ["kivof.com", "adiy.ch/cheese"],
    note: "Cheese Factory × Kivof · Hackathon HPE & NVIDIA · Ginebra",
  },
};
