import type { DeckCopy, DeckLabels } from "./types";
export const frLabels: DeckLabels = {
  startDemo: "Démarrer une nouvelle démo",
  loadDemo: "Charger l’espace de travail",
  loadReplay: "Charger la scène enregistrée",
  loading: "Ouverture…",
  demoError:
    "Impossible d’ouvrir la démo. Réessayez ou ouvrez-la dans un nouvel onglet.",
  open: "Ouvrir dans un nouvel onglet",
  reload: "Recharger la démo",
  mediaNote:
    "Si la vue intégrée est indisponible, ouvrez-la dans un nouvel onglet.",
  inactiveMedia: "Ouvrez cette diapositive pour lire ou explorer.",
  recording: "Démonstration enregistrée",
  interactive: "Démo interactive",
  jump: "Choisir une diapositive",
  keyboard: "← → pour naviguer",
  modelTask: "Tâche du modèle",
  correctImages: "Images correctes",
  accuracy: "Exactitude",
  macroF1: "Macro-F1",
  cheeseType: "Type de fromage",
  destination: "Bac de destination",
  bins: ["Dure", "Mi-dure", "Molle", "Fraîche", "Persillée"],
  source: "Image du projet fournie",
};
export const fr: DeckCopy = {
  hero: {
    label: "HPE × NVIDIA / GENÈVE",
    title: "IA physique.\nCheese Factory.",
    body: "Tri guidé par caméra. Des preuves à explorer.",
    points: ["Une usine simulée", "Chaque décision, vue par l’opérateur"],
    note: "Cheese Factory × Kivof · Septembre 2026",
  },
  task: {
    label: "01 / LA TÂCHE",
    title: "Onze types de fromage.\nCinq destinations.",
    body: "Une décision de tri claire commence par le produit devant la caméra.",
    points: [
      "Pâte dure · Emmental",
      "Pâte mi-dure · Raclette",
      "Pâte molle · Chèvre mou · Fromage fondu",
      "Fromage frais · Cottage · Fromage à tartiner",
      "Pâte persillée",
    ],
    note: "Les produits incertains ou autres que le fromage suivent une voie de rejet séparée.",
  },
  capture: {
    label: "01 / DE LA CAMÉRA À LA PRISE",
    title: "Observer. Classer.\nVérifier. Déposer.",
    body: "La décision conserve l’image et la position qui l’ont produite.",
    points: [
      "Capturer\nImage et position",
      "Classer\nType de fromage et bac",
      "Vérifier\nProduit, image et confiance",
      "Saisir et déposer\nMouvement Franka dans Isaac Sim",
    ],
    note: "Des preuves incertaines ou contradictoires immobilisent le bras.",
  },
  training: {
    label: "01 / ENTRAÎNEMENT",
    title: "Des images annotées\nau modèle de tri.",
    body: "Entraînement ConvNeXt sous PyTorch, avec une entrée de 384 px.",
    points: ["Découpes annotées", "Prototype Replicator ultérieur"],
    note: "Les vues liées restent dans la même partition. La grille Replicator est un prototype, pas un jeu d’entraînement de production.",
  },
  clearance: {
    label: "01 / LA CELLULE ROBOTIQUE",
    title: "Donner au bras\nl’espace de bouger.",
    body: "Dégagement et géométrie de collision font partie de la conception de la tâche.",
    points: [
      "Poteaux hors de la portée nominale",
      "Géométrie du portique en physique et planification",
    ],
    note: "Vérification fournie par l’équipe : 10 prises + 1 rejet avec annotations prédéfinies. Elle teste le mouvement, pas la reconnaissance.",
  },
  scores: {
    label: "01 / IMAGES RÉSERVÉES",
    title: "Mesurer la reconnaissance\nsur des images inédites.",
    body: "Deux tâches de modèle. Deux jeux d’images de test distincts.",
    points: [],
    note: "Résultats de la version 9 fournie. Macro-F1 pondère les classes également ; ces scores n’établissent pas la fiabilité de toute l’usine.",
  },
  outcomes: {
    label: "01 / LE PARCOURS EN USINE",
    title: "Reconnaître reste\nle défi le plus difficile.",
    body: "Un parcours de onze produits rend l’écart visible.",
    points: [
      "Décisions du modèle\n3 déposes + 1 rejet",
      "Annotations prédéfinies\nVérification du mouvement uniquement",
    ],
    note: "10 fromages + 1 autre produit. Les quatre prises tentées ont abouti. Parcours de la version 9 fournie.",
  },
  video1: {
    label: "02 / FILM 01",
    title: "Voir l’usine\nen mouvement.",
    body: "La démonstration fournie, dans son propre cadre.",
    points: [],
    note: "Vidéo enregistrée · Démarre sans son. Activez le son dans le lecteur.",
  },
  operator: {
    label: "02 / L’OPÉRATEUR",
    title: "Voir pourquoi\nle bras s’arrête.",
    body: "Image capturée. Prédictions contradictoires. Motif d’arrêt visible.",
    points: [
      "Conserver la décision avec sa source",
      "Examiner l’incertitude avant la prochaine prise",
    ],
    note: "Capture du tableau de bord fournie, issue d’une vérification distincte.",
  },
  replay: {
    label: "02 / EXPLORER LA RELECTURE",
    title: "Choisir l’instant.\nChanger le point de vue.",
    body: "Explorez la scène Cheese Factory enregistrée.",
    points: [],
    note: "adiy.ch/cheese · Scène enregistrée interactive ; aucune session Isaac active n’est nécessaire pour le visiteur.",
  },
  video2: {
    label: "02 / FILM 02",
    title: "Regarder\nde plus près.",
    body: "Une deuxième démonstration fournie.",
    points: [],
    note: "Vidéo enregistrée · Démarre sans son. Activez le son dans le lecteur.",
  },
  export: {
    label: "02 / PARTAGER LA SCÈNE",
    title: "Enregistrer une fois.\nExplorer dans le navigateur.",
    body: "Isaac Web Exporter prépare une scène pour d’autres instants et points de vue.",
    points: [
      "Capturer\nMouvement compatible en USD",
      "Assembler\nGéométrie GLB, mouvement et JSON",
      "Publier\nThree.js / WebGL",
    ],
    note: "L’usine utilise un adaptateur de capture spécifique. La relecture web est de la 3D enregistrée, pas du pilotage du simulateur.",
  },
  workspace: {
    label: "03 / KIVOF",
    title: "Un parcours est\nplus qu’une vidéo.",
    body: "Réunir observations, explications et annotations vérifiées dans un même espace.",
    points: [
      "Examiner les preuves",
      "Comprendre le résultat",
      "Garder la prochaine amélioration traçable",
    ],
    note: "Image d’inspection Isaac de Kivof enregistrée · Avant la prise.",
  },
  workflow: {
    label: "03 / LA BOUCLE DE REVUE",
    title: "D’un parcours\nà une prochaine étape vérifiée.",
    body: "Conserver réussites et échecs pour les examiner.",
    points: [
      "Observer\nParcours et preuves capteurs",
      "Comprendre\nExplications fondées",
      "Évaluer\nRésultats de tâches délimitées",
      "Améliorer\nAnnotation vérifiée",
    ],
    note: "Les prédictions originales sont conservées lorsqu’une personne corrige une annotation.",
  },
  demo: {
    label: "03 / OUVRIR KIVOF",
    title: "Explorer\nl’espace de travail.",
    body: "Lancez un scénario, examinez ses preuves et révisez une annotation.",
    points: [],
    note: "Application en direct. Les essais d’usine restent simulés ; aucun mouvement physique n’est autorisé.",
  },
  boundary: {
    label: "03 / LA LIMITE DE CONTRÔLE",
    title: "Expliquer au centre.\nAgir localement.",
    body: "La conversation de l’opérateur reste séparée de l’autorité sur les moteurs.",
    points: [
      "Espace navigateur\nPreuves et discussion",
      "Services Rust + OpenClaw\nOrchestration authentifiée",
      "Contrôleur local\nAutorité d’exécution",
    ],
    note: "Une explication n’est ni une approbation de sécurité ni une commande moteur.",
  },
  native: {
    label: "03 / SIMULATION NATIVE",
    title: "La physique, avec\ndes preuves examinables.",
    body: "Une image Isaac enregistrée accompagne le mouvement mesuré du robot et sa dépose.",
    points: [
      "Caméra et échantillons articulaires enregistrés",
      "Ouverture, levage et distance au bac mesurés",
    ],
    note: "Vérification native Kivof : objet rigide coloré et perception expérimentale par couleur. Aucun classificateur de fromage entraîné ni robot physique dans cette vérification.",
  },
  video3: {
    label: "03 / FILM 03",
    title: "Du parcours\nà ses preuves.",
    body: "La troisième démonstration fournie.",
    points: [],
    note: "Vidéo enregistrée · Démarre sans son. Activez le son dans le lecteur.",
  },
  exporterIntro: {
    label: "02 / ISAAC WEB EXPORTER",
    title: "Une scène enregistrée.\nUn site interactif.",
    body: "Partager la scène sans demander au visiteur d’installer Isaac.",
    points: ["Choisir l’instant", "Choisir l’angle de caméra"],
    note: "Relecture 3D enregistrée. Le visiteur ne pilote pas le simulateur.",
  },
  viewer: {
    label: "02 / LE VISIONNEUR",
    title: "Examiner un instant.\nExaminer un objet.",
    body: "Mettre la vidéo en pause, puis explorer l’essentiel.",
    points: [
      "Avancer d’une image",
      "Centrer sur un élément",
      "Isoler un produit",
    ],
    note: "Interface Isaac Web Exporter fournie. Scène enregistrée à 35 secondes.",
  },
  formats: {
    label: "02 / TROIS FAÇONS DE PARTAGER",
    title: "Vidéo. Isaac en direct.\nRelecture web.",
    body: "Choisir le format adapté à la revue.",
    points: [
      "Vidéo\nVue caméra enregistrée\nChoisir l’instant\nPartager un fichier vidéo",
      "Isaac en direct\nSession interactive en direct\nPiloter le simulateur\nGarder l’hôte actif",
      "Export web\nScène 3D enregistrée\nChoisir l’instant et la caméra\nPublier des fichiers statiques",
    ],
    note: "La relecture web offre un autre angle sans garder Isaac en fonctionnement.",
  },
  replayInvite: {
    label: "02 / ESSAYER LA RELECTURE",
    title: "L’usine,\nprête à explorer.",
    body: "Mettre une prise en pause. Changer de vue.",
    points: ["adiy.ch/cheese", "Isaac Web Exporter"],
    note: "Scène Cheese Factory enregistrée · gr9aditya/isaac-web-exporter.",
  },
  closing: {
    label: "IA PHYSIQUE / CHEESE FACTORY",
    title: "Mettre une prise en pause.\nPoser une question.",
    body: "Explorons les preuves ensemble.",
    points: ["kivof.com", "adiy.ch/cheese"],
    note: "Cheese Factory × Kivof · Hackathon HPE & NVIDIA · Genève",
  },
};
